### ISSUE TITLE
plot_EEG method doesn't accept list of electrode str's

### ISSUE THREAD

**Issue by dwivedilab** [dwivedilab/dlab#9]
For some reason, the plot_EEG function, electrode argument, is not accepting the list of electrodes. 
Does still work with Preset lists (e.g. 'midlines')

Example:
![image](https://user-images.githubusercontent.com/40637394/47866940-804bef00-ddd6-11e8-831f-60f8c6405bbe.png)

**Comment by jselvan** [comment]
It seems that when we added the electrode_layouts in settings and allowed strings to be used to specify layouts, I used the "get" method to resolve accessing the self.settings.electrode_layouts dict.

This issue shows up in a few places in EEG and BEH which presumably were not discovered because we primarily used predefined presets.

It is now resolved by the 'get' function only being executed when the argument is a string.

Resolved in commit b4a2aa6f
